# $Id: Makefile.example 17 2012-01-14 23:01:14Z kate $

# TODO: this makefile is portable, and gets installed to share/examples as "Makefile"

router: router.o
	${CC} ${LDFLAGS} -o router router.o -lcl

router.o: router.c
	${CC} ${CFLAGS} -c router.c

