name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-16.04, ubuntu-18.04 ]
        cc: [ clang, gcc ]
        make: [ bmake, pmake ]
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: dependencies
      run: sudo apt-get install pmake bmake libtelnet-dev libunibilium-dev libtermkey-dev

    - name: make
      run: ${{ matrix.make }} -r PKGCONF=pkg-config CC=${{ matrix.cc }}

    - name: test
      run: ${{ matrix.make }} -r PKGCONF=pkg-config test

    - name: install
      run: ${{ matrix.make }} -r PKGCONF=pkg-config PREFIX=/tmp/p install
