name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: dependencies
      run: sudo apt-get install bmake libtelnet-dev libunibilium-dev libtermkey-dev

    - name: make
      run: bmake -r PKGCONF=pkg-config CC=gcc

    - name: test
      run: bmake -r test

    - name: install
      run: bmake -r PREFIX=/tmp/p install
