name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-16.04, ubuntu-18.04 ]
    
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: dependencies
      run: sudo apt-get install bmake libtelnet-dev libunibilium-dev libtermkey-dev

    - name: make
      run: bmake -r PKGCONF=pkg-config CC=gcc

    - name: test
      run: bmake -r PKGCONF=pkg-config test

    - name: install
      run: bmake -r PKGCONF=pkg-config PREFIX=/tmp/p install
